export function getMeta() {
    return {
        name: 'root',
        component: 'Layout',
        className: 'ttk-es-app-workbench',
        children:[
            {
                name:'quota',
                component:'::div',
                className:'ttk-es-app-workbench-quota',
                children:[
                    {
                        name:'item',
                        component:'::div',
                        className:'ttk-es-app-workbench-quota-item',
                        children:[
                            {
                                name:'index',
                                component:'::div',
                                className:'ttk-es-app-workbench-quota-item-index',
                                children:[
                                    {
                                        name:'title',
                                        component:'::div',
                                        className:'ttk-es-app-workbench-quota-item-index-title',
                                        children:[
                                            {
                                                name:'graph',
                                                component:'::div',
                                                className:'ttk-es-app-workbench-quota-item-index-title-value',
                                                children:'本月商机转化率'
                                            },
                                            {
                                                name: 'popover',
                                                component: 'Popover',
                                                content: 'aaaaaaa',
                                                placement: 'bottom',
                                                overlayClassName: 'ttk-es-app-workbench-quota-item-index-title-popover',
                                                children: {
                                                    name: 'infoIcon',
                                                    component: 'Icon',
                                                    fontFamily: 'edficon',
                                                    type: 'tishi'
                                                }
                                            }
                                        ]
                                    },
                                    {
                                        name:'graph',
                                        component:'::div',
                                        className:'ttk-es-app-workbench-quota-item-index-graph',
                                        children:[
                                            {
                                                name:'value',
                                                component:'::div',
                                                className:'ttk-es-app-workbench-quota-item-index-graph-value',
                                                children:'98%'
                                            },
                                            {
                                                name:'img',
                                                component:'::div',
                                                className:'ttk-es-app-workbench-quota-item-index-graph-img',
                                                id: 'biz',
                                                children: '{{$setChartBusinessRate()}}'
                                            }
                                        ]
                                    },
                                    {
                                        name:'tip',
                                        component:'::div',
                                        className:'ttk-es-app-workbench-quota-item-index-tip',
                                        children:[
                                            {
                                                name:'item',
                                                component:'::div',
                                                className:'ttk-es-app-workbench-quota-item-index-tip-item',
                                                children:[
                                                    {
                                                        name:'title',
                                                        component:'::div',
                                                        className:'ttk-es-app-workbench-quota-item-index-tip-item-title',
                                                        children:'本月新增'
                                                    },
                                                    {
                                                        name:'value',
                                                        component:'::div',
                                                        className:'ttk-es-app-workbench-quota-item-index-tip-item-value',
                                                        children:'6'
                                                    },
                                                    {
                                                        name:'unit',
                                                        component:'::div',
                                                        className:'ttk-es-app-workbench-quota-item-index-tip-item-unit',
                                                        children:'户'
                                                    }
                                                ]
                                            },
                                            {
                                                name:'item',
                                                component:'::div',
                                                className:'ttk-es-app-workbench-quota-item-index-tip-item',
                                                children:[
                                                    {
                                                        name:'title',
                                                        component:'::div',
                                                        className:'ttk-es-app-workbench-quota-item-index-tip-item-title',
                                                        children:'本月签约'
                                                    },
                                                    {
                                                        name:'value',
                                                        component:'::div',
                                                        className:'ttk-es-app-workbench-quota-item-index-tip-item-value',
                                                        children:'360'
                                                    },
                                                    {
                                                        name:'unit',
                                                        component:'::div',
                                                        className:'ttk-es-app-workbench-quota-item-index-tip-item-unit',
                                                        children:'户'
                                                    }
                                                ]
                                            },
                                        ]
                                    },
                                ]
                            },
                            {
                                name:'index',
                                component:'::div',
                                className:'ttk-es-app-workbench-quota-item-index1',
                                children:[
                                    {
                                        name:'top',
                                        component:'::div',
                                        className:'ttk-es-app-workbench-quota-item-index1-top',
                                        children:[
                                            {
                                                name:'title',
                                                component:'::div',
                                                className:'ttk-es-app-workbench-quota-item-index1-top-title',
                                                children:[
                                                    {
                                                        name:'graph',
                                                        component:'::div',
                                                        className:'ttk-es-app-workbench-quota-item-index1-top-title-value',
                                                        children:'本月新增客户'
                                                    },
                                                    {
                                                        name: 'infoIcon',
                                                        component: 'Icon',
                                                        fontFamily: 'edficon',
                                                        type: 'tishi'
                                                    }
                                                ]
                                            },
                                            {
                                                name:'value',
                                                component:'::div',
                                                className:'ttk-es-app-workbench-quota-item-index1-top-value',
                                                children:'846'
                                            },
                                        ]
                                    },
                                    {
                                        name:'bottom',
                                        component:'::div',
                                        className:'ttk-es-app-workbench-quota-item-index1-bottom',
                                        children:[
                                            {
                                                name:'item',
                                                component:'::div',
                                                className:'ttk-es-app-workbench-quota-item-index1-bottom-item',
                                                children:[
                                                    {
                                                        name:'title',
                                                        component:'::div',
                                                        className:'ttk-es-app-workbench-quota-item-index1-bottom-item-title',
                                                        children:'本月停止'
                                                    },
                                                    {
                                                        name:'detail',
                                                        component:'::div',
                                                        className:'ttk-es-app-workbench-quota-item-index1-bottom-item-detail',
                                                        children:[
                                                            {
                                                                name:'value',
                                                                component:'::div',
                                                                className:'ttk-es-app-workbench-quota-item-index1-bottom-item-detail-value',
                                                                children:'23'
                                                            },
                                                            {
                                                                name:'unit',
                                                                component:'::div',
                                                                className:'ttk-es-app-workbench-quota-item-index1-bottom-item-detail-unit',
                                                                children:'户'
                                                            }
                                                        ]
                                                    }
                                                ]
                                            },
                                            {
                                                name:'item',
                                                component:'::div',
                                                className:'ttk-es-app-workbench-quota-item-index1-bottom-item',
                                                children:[
                                                    {
                                                        name:'title',
                                                        component:'::div',
                                                        className:'ttk-es-app-workbench-quota-item-index1-bottom-item-title',
                                                        children:'累计客户'
                                                    },
                                                    {
                                                        name:'detail',
                                                        component:'::div',
                                                        className:'ttk-es-app-workbench-quota-item-index1-bottom-item-detail',
                                                        children:[
                                                            {
                                                                name:'value',
                                                                component:'::div',
                                                                className:'ttk-es-app-workbench-quota-item-index1-bottom-item-detail-value',
                                                                children:'12,223'
                                                            },
                                                            {
                                                                name:'unit',
                                                                component:'::div',
                                                                className:'ttk-es-app-workbench-quota-item-index1-bottom-item-detail-unit',
                                                                children:'户'
                                                            }
                                                        ]
                                                    }
                                                ]
                                            },
                                        ]
                                    },
                                ]
                            }
                        ]
                    },
                    {
                        name:'item',
                        component:'::div',
                        className:'ttk-es-app-workbench-quota-item',
                        children:[
                            {
                                name:'index',
                                component:'::div',
                                className:'ttk-es-app-workbench-quota-item-index1',
                                children:[
                                    {
                                        name:'top',
                                        component:'::div',
                                        className:'ttk-es-app-workbench-quota-item-index1-top',
                                        children:[
                                            {
                                                name:'title',
                                                component:'::div',
                                                className:'ttk-es-app-workbench-quota-item-index1-top-title',
                                                children:[
                                                    {
                                                        name:'graph',
                                                        component:'::div',
                                                        className:'ttk-es-app-workbench-quota-item-index1-top-title-value',
                                                        children:'本月欠费'
                                                    },
                                                    {
                                                        name: 'infoIcon',
                                                        component: 'Icon',
                                                        fontFamily: 'edficon',
                                                        type: 'tishi'
                                                    }
                                                ]
                                            },
                                            {
                                                name:'value',
                                                component:'::div',
                                                className:'ttk-es-app-workbench-quota-item-index1-top-value',
                                                children:'￥ 126,560.00'
                                            },
                                        ]
                                    },
                                    {
                                        name:'bottom',
                                        component:'::div',
                                        className:'ttk-es-app-workbench-quota-item-index1-bottom',
                                        children:[
                                            {
                                                name:'item',
                                                component:'::div',
                                                className:'ttk-es-app-workbench-quota-item-index1-bottom-item1',
                                                children:[
                                                    {
                                                        name:'title',
                                                        component:'::div',
                                                        className:'ttk-es-app-workbench-quota-item-index1-bottom-item1-title',
                                                        children:'本月支出'
                                                    },
                                                    {
                                                        name:'value',
                                                        component:'::div',
                                                        className:'ttk-es-app-workbench-quota-item-index1-bottom-item1-value',
                                                        children:'￥3265.00'
                                                    }
                                                ]
                                            },
                                            {
                                                name:'item',
                                                component:'::div',
                                                className:'ttk-es-app-workbench-quota-item-index1-bottom-item1',
                                                children:[
                                                    {
                                                        name:'title',
                                                        component:'::div',
                                                        className:'ttk-es-app-workbench-quota-item-index1-bottom-item1-title',
                                                        children:'累计客户'
                                                    },
                                                    {
                                                        name:'value',
                                                        component:'::div',
                                                        className:'ttk-es-app-workbench-quota-item-index1-bottom-item1-value',
                                                        children:'￥12,223.00'
                                                    }
                                                ]
                                            },
                                        ]
                                    },
                                ]
                            },
                            {
                                name:'index2',
                                component:'::div',
                                className:'ttk-es-app-workbench-quota-item-index2',
                                children:[
                                    {
                                        name:'items',
                                        component:'::div',
                                        className:'ttk-es-app-workbench-quota-item-index2-items',
                                        children:[
                                            {
                                                name:'title',
                                                component:'::div',
                                                className:'ttk-es-app-workbench-quota-item-index2-items-title',
                                                children:[
                                                    {
                                                        name:'graph',
                                                        component:'::div',
                                                        className:'ttk-es-app-workbench-quota-item-index2-items-title-value',
                                                        children:'合同'
                                                    },
                                                    {
                                                        name: 'infoIcon',
                                                        component: 'Icon',
                                                        fontFamily: 'edficon',
                                                        type: 'tishi'
                                                    }
                                                ]
                                            },
                                            {
                                                name:'detail',
                                                component:'::div',
                                                className:'ttk-es-app-workbench-quota-item-index2-items-detail',
                                                children:[
                                                    {
                                                        name:'li',
                                                        component:'::div',
                                                        className:'ttk-es-app-workbench-quota-item-index2-items-detail-li',
                                                        children:[
                                                            {
                                                                name:'title',
                                                                component:'::div',
                                                                className:'ttk-es-app-workbench-quota-item-index2-items-detail-li-title',
                                                                children:'本月新增'
                                                            },
                                                            {
                                                                name:'value',
                                                                component:'::div',
                                                                className:'ttk-es-app-workbench-quota-item-index2-items-detail-li-value',
                                                                children:'888'
                                                            }
                                                        ]
                                                    },
                                                    {
                                                        name:'li',
                                                        component:'::div',
                                                        className:'ttk-es-app-workbench-quota-item-index2-items-detail-li',
                                                        children:[
                                                            {
                                                                name:'title',
                                                                component:'::div',
                                                                className:'ttk-es-app-workbench-quota-item-index2-items-detail-li-title',
                                                                children:'服务到期'
                                                            },
                                                            {
                                                                name:'value',
                                                                component:'::div',
                                                                className:'ttk-es-app-workbench-quota-item-index2-items-detail-li-value',
                                                                children:'103'
                                                            }
                                                        ]
                                                    },
                                                ]
                                            }
                                        ]
                                    },
                                    {
                                        name:'items',
                                        component:'::div',
                                        className:'ttk-es-app-workbench-quota-item-index2-items',
                                        children:[
                                            {
                                                name:'title',
                                                component:'::div',
                                                className:'ttk-es-app-workbench-quota-item-index2-items-title',
                                                children:'任务'
                                            },
                                            {
                                                name:'detail',
                                                component:'::div',
                                                className:'ttk-es-app-workbench-quota-item-index2-items-detail',
                                                children:[
                                                    {
                                                        name:'li',
                                                        component:'::div',
                                                        className:'ttk-es-app-workbench-quota-item-index2-items-detail-li',
                                                        children:[
                                                            {
                                                                name:'title',
                                                                component:'::div',
                                                                className:'ttk-es-app-workbench-quota-item-index2-items-detail-li-title',
                                                                children:'本月新增'
                                                            },
                                                            {
                                                                name:'value',
                                                                component:'::div',
                                                                className:'ttk-es-app-workbench-quota-item-index2-items-detail-li-value',
                                                                children:'888'
                                                            }
                                                        ]
                                                    },
                                                    {
                                                        name:'li',
                                                        component:'::div',
                                                        className:'ttk-es-app-workbench-quota-item-index2-items-detail-li',
                                                        children:[
                                                            {
                                                                name:'title',
                                                                component:'::div',
                                                                className:'ttk-es-app-workbench-quota-item-index2-items-detail-li-title',
                                                                children:'本月完成'
                                                            },
                                                            {
                                                                name:'value',
                                                                component:'::div',
                                                                className:'ttk-es-app-workbench-quota-item-index2-items-detail-li-value',
                                                                children:'103'
                                                            }
                                                        ]
                                                    },
                                                ]
                                            }
                                        ]
                                    },
                                ]
                            }
                        ]
                    }
                ]
            },
            {
                name:'chart',
                component:'::div',
                className:'ttk-es-app-workbench-chart',
                children:[
                    {
                        name:'item',
                        component:'::div',
                        className:'ttk-es-app-workbench-chart-item',
                        children:[
                            {
                                name:'title',
                                component:'::div',
                                className:'ttk-es-app-workbench-chart-item-title',
                                children:[
                                    {
                                        name:'value',
                                        component:'::div',
                                        className:'ttk-es-app-workbench-chart-item-title-value',
                                        children:'收支概览'
                                    },
                                    {
                                        name:'button',
                                        component:'::a',
                                        className:'ttk-es-app-workbench-chart-item-title-button',
                                        children:'本年'
                                    }
                                ]
                            },
                            {
                                name:'line',
                                component:'::div',
                                className:'ttk-es-app-workbench-chart-item-line',
                                id: 'budgetLine',
                                children: '{{$setChartBudgetLine()}}'
                            }
                        ]
                    },
                    {
                        name:'item',
                        component:'::div',
                        className:'ttk-es-app-workbench-chart-item',
                        children:[
                            {
                                name:'title',
                                component:'::div',
                                className:'ttk-es-app-workbench-chart-item-title',
                                children:[
                                    {
                                        name:'value',
                                        component:'::div',
                                        className:'ttk-es-app-workbench-chart-item-title-value',
                                        children:'收费排名'
                                    },
                                    {
                                        name:'button',
                                        component:'::div',
                                        className:'ttk-es-app-workbench-chart-item-title-button',
                                        children:[
                                            {
                                                name:'a',
                                                component:'::div',
                                                className:'{{data.currentChangeBarActive==="1"?"ttk-es-app-workbench-chart-item-title-button-a active":"ttk-es-app-workbench-chart-item-title-button-a"}}',
                                                children:'本月',
                                                onClick:'{{function(){$chargeBarTabChange("1")}}}'
                                            },
                                            {
                                                name:'a',
                                                component:'::div',
                                                className:'{{data.currentChangeBarActive==="2"?"ttk-es-app-workbench-chart-item-title-button-a active":"ttk-es-app-workbench-chart-item-title-button-a"}}',
                                                children:'本季',
                                                onClick:'{{function(){$chargeBarTabChange("2")}}}'
                                            },
                                            {
                                                name:'a',
                                                component:'::div',
                                                className:'{{data.currentChangeBarActive==="3"?"ttk-es-app-workbench-chart-item-title-button-a active":"ttk-es-app-workbench-chart-item-title-button-a"}}',
                                                children:'本年',
                                                onClick:'{{function(){$chargeBarTabChange("3")}}}'
                                            }
                                        ]
                                    }
                                ]
                            },
                            {
                                name:'line',
                                component:'::div',
                                className:'ttk-es-app-workbench-chart-item-line',
                                id: 'budgetLine',
                                children: '{{$setChartChargeBar()}}'
                            }
                        ]
                    }
                ]
            },
            {
                name:'business',
                component:'::div',
                className:'ttk-es-app-workbench-business',
                children:[
                    {
                        name:'title',
                        component:'::div',
                        className:'ttk-es-app-workbench-business-title',
                        children:[
                            {
                                name:'value',
                                component:'::div',
                                className:'ttk-es-app-workbench-business-title-value',
                                children:'商机分析'
                            }
                        ]
                    },
                    {
                        name:'detail',
                        component:'::div',
                        className:'ttk-es-app-workbench-business-detail',
                        children:[
                            {
                                name:'chart1',
                                component:'::div',
                                className:'ttk-es-app-workbench-business-detail-chart ttk-es-app-workbench-business-detail-chart1',
                                id: 'budgetLine',
                                children: '{{$setChartBusinessPie()}}'
                            },
                            {
                                name:'chart2',
                                component:'::div',
                                className:'ttk-es-app-workbench-business-detail-chart ttk-es-app-workbench-business-detail-chart2',
                                id: 'budgetLine',
                                children: '{{$setChartBusinessTypePie()}}'
                            },
                            {
                                name:'chart3',
                                component:'::div',
                                className:'ttk-es-app-workbench-business-detail-chart ttk-es-app-workbench-business-detail-chart3',
                                id: 'budgetLine',
                                children: '{{$setChartCustomerRador()}}'
                            },
                        ]
                    }
                ]
            },
            {
                name:'customer',
                component:'::div',
                className:'ttk-es-app-workbench-customer',
                children:[
                    {
                        name:'title',
                        component:'::div',
                        className:'ttk-es-app-workbench-customer-title',
                        children:[
                            {
                                name:'value',
                                component:'::div',
                                className:'ttk-es-app-workbench-customer-title-value',
                                children:'客户分析'
                            }
                        ]
                    },
                    {
                        name:'detail',
                        component:'::div',
                        className:'ttk-es-app-workbench-customer-detail',
                        children:[
                            {
                                name:'chart1',
                                component:'::div',
                                className:'ttk-es-app-workbench-customer-detail-chart ttk-es-app-workbench-customer-detail-chart1',
                                id: 'budgetLine',
                                children: '{{$setChartCustomerLine()}}'
                            },
                            {
                                name:'chart2',
                                component:'::div',
                                className:'ttk-es-app-workbench-customer-detail-chart ttk-es-app-workbench-customer-detail-chart2',
                                id: 'budgetLine',
                                children: '{{$setChartCustomerPie()}}'
                            },
                        ]
                    }
                ]
            },
        ]
    }
}

export function getInitState() {
    return {
        data:{
            chargeBarLoading:false,
            currentChangeBarActive:'1',
            chargeBarData:[10, 52, 200, 334, 390, 330, 220,333,222,45]
        }
    }
}