export const generalBtnType = [
  /* {
               name: 'invoice',
               className: 'header-btn',
               type: 'primary',
               children: '发票管理工具',
               key: 'invoiceManagement',
               disabled: false,
             },*/
  {
    name: "sale",
    className: "header-btn",
    type: "primary",
    children: "一键读取销项",
    key: "loadSaleInvoice",
    disabled: false,
    tooltipKey: true,
  },
  {
    name: "purchase",
    className: "header-btn",
    type: "primary",
    children: "一键读取进项",
    key: "loadPurchaseInvoice",
    disabled: false,
    tooltipKey: true,
  },
  {
    name: "invoice",
    className: "header-btn",
    type: "",
    children: "上期留抵税额",
    key: "sqldse",
    disabled: false,
  },
  {
    name: "invoice",
    className: "header-btn",
    type: "",
    children: "导出",
    key: "exports",
    disabled: false,
  },
]

export const smallBtnType = [
  {
    name: "sale",
    className: "header-btn",
    type: "primary",
    children: "一键读取销项",
    key: "loadSaleInvoice",
    disabled: false,
    tooltipKey: true,
  },
  {
    name: "purchase",
    className: "header-btn",
    type: "primary",
    children: "一键读取进项",
    key: "loadPurchaseInvoice",
    disabled: false,
    tooltipKey: true,
  },
  {
    name: "limit",
    className: "header-btn",
    type: "primary",
    children: "上限预警",
    key: "setLimitData",
  },
  {
    name: "invoice",
    className: "header-btn",
    type: "",
    children: "导出",
    key: "exports",
    disabled: false,
  },
]

/*非网报区一般纳税人*/
export const generalBtnType_NonNetwork = [
  {
    name: "salesAndPurchase",
    className: "header-btn",
    type: "primary",
    children: "一键读取销进项",
    key: "salesAndPurchase",
    disabled: false,
    tooltipKey: true,
  },
  // {
  //   name: 'loadPlatform',
  //   className: 'header-btn',
  //   type: 'Dropdown',
  //   children: '平台采集',
  //   key: 'loadPlatform',
  //   disabled: false,
  //   tooltipKey: true,
  //   menuItems: [{
  //      name: 'cancelBtn',
  //      key: 'cancelPlatform',
  //      children: '取消任务',
  //      disabled: false,
  //   }]
  // },
  /* {
               name: 'invoice',
               className: 'header-btn',
               type: 'primary',
               children: '发票管理工具',
               key: 'invoiceManagement',
               disabled: false,
             },*/
  {
    name: "invoice",
    className: "header-btn",
    type: "",
    children: "上期留抵税额",
    key: "sqldse",
    disabled: false,
  },
  {
    name: "invoice",
    className: "header-btn",
    type: "",
    children: "导出",
    key: "exports",
    disabled: false,
  },
]

/*非网报区小规模*/
export const smallBtnType_NonNetwork = [
  {
    name: "salesAndPurchase",
    className: "header-btn",
    type: "primary",
    children: "一键读取销进项",
    key: "salesAndPurchase",
    disabled: false,
    tooltipKey: true,
  },
  // {
  //   name: 'loadPlatform',
  //   className: 'header-btn',
  //   type: 'Dropdown',
  //   children: '平台采集',
  //   key: 'loadPlatform',
  //   disabled: false,
  //   tooltipKey: true,
  //   menuItems: [{
  //      name: 'cancelBtn',
  //      key: 'cancelPlatform',
  //      children: '取消任务',
  //      disabled: false,
  //   }]
  // },
  {
    name: "limit",
    className: "header-btn",
    type: "primary",
    children: "上限预警",
    key: "setLimitData",
  },
  {
    name: "invoice",
    className: "header-btn",
    type: "",
    children: "导出",
    key: "exports",
    disabled: false,
  },
]

export const Tips = {
  "0": {
    loadSaleInvoice: [
      {
        title: "温馨提示：",
        content: "读取所选月份开具发票。",
      },
    ],
    loadPurchaseInvoice: [
      {
        title: "温馨提示：",
        content: "读取所选月份认证发票和开具发票",
      },
      {
        title: "",
        content: "读取票税宝所选月份上传发票",
      },
    ],
  },
  "1": {
    loadSaleInvoice: [
      {
        title: "温馨提示：",
        content: "读取所选月份开具发票",
      },
    ],
    loadPurchaseInvoice: [
      {
        title: "温馨提示：",
        content: "读取所选月份开具或票税宝上传的发票。",
      },
    ],
  },
}

export const nonNetworkTips = [
  {
    title: "温馨提示：",
    content: "1、本途径，是获取金财代账云端数据，包含：",
  },
  {
    title: "",
    content: "【发票管理工具、票税宝、平台采集】已上传的发票；",
  },
  {
    title: "",
    content: "2、销项，读取的是所选月份开具的发票；",
  },
  {
    title: "",
    content: "3、进项，读取的是所选月份开具和认证的发票，以及票税宝所选月份上传的发票。",
  },
]

export const columnData = {
  0: {
    columns: [
      {
        id: "khmc",
        caption: "客户名称",
        fieldName: "khmc",
        isFixed: true, // 是否要固定
        isVisible: true, // 根据后台返回值判断是否显示
        width: 290,
        isMustSelect: true, // 是否必选
        align: "",
      },
      {
        id: "mneCode",
        caption: "助记码",
        fieldName: "mneCode",
        isFixed: false,
        isVisible: false,
        width: 100,
        isMustSelect: false,
        align: "",
      },
      {
        id: "xxfp",
        caption: "销项发票",
        fieldName: "xxfp",
        isVisible: true,
        isMustSelect: true,
        align: "",
        width: 400,
        children: [
          {
            caption: "份数",
            fieldName: "xxfpfs",
            isFixed: false,
            isVisible: true,
            isSubTitle: true,
            width: 80,
            align: "",
            amount: false,
          },
          {
            caption: "金额",
            fieldName: "xxhjje",
            isFixed: false,
            isVisible: true,
            isSubTitle: true,
            //width: 120,
            align: "",
            className: "table_td_align_right",
            amount: true,
          },
          {
            caption: "税额",
            fieldName: "xxhjse",
            isFixed: false,
            isVisible: true,
            isSubTitle: true,
            //width: 120,
            align: "",
            className: "table_td_align_right",
            amount: true,
          },
          {
            caption: "状态",
            fieldName: "xxcjzt",
            isFixed: false,
            isVisible: true,
            isSubTitle: false,
            width: 60,
            align: "center",
            type: "xx",
          },
        ],
      },
      {
        id: "jxfpyrz",
        caption: "进项发票（已认证）",
        isVisible: true,
        isMustSelect: true,
        align: "",
        fieldName: "jxfpyrz",
        width: 400,
        children: [
          {
            caption: "份数",
            fieldName: "jxfpfsyrz",
            isFixed: false,
            isVisible: true,
            isSubTitle: true, // 判断是否为二级表头 ***** 实际为显示一级表头内容
            width: 80,
            align: "",
            amount: false,
          },
          {
            caption: "金额",
            fieldName: "jxhjjeyrz",
            isFixed: false,
            isVisible: true,
            isSubTitle: true,
            //width: 120,
            align: "",
            className: "table_td_align_right",
            amount: true,
          },
          {
            caption: "税额",
            fieldName: "jxhjseyrz",
            isFixed: false,
            isVisible: true,
            isSubTitle: true,
            //width: 120,
            align: "",
            className: "table_td_align_right",
            amount: true,
          },
          {
            caption: "有效税额",
            fieldName: "jxhjseyxseyrz",
            isFixed: false,
            isVisible: true,
            isSubTitle: true,
            //width: 80,
            align: "",
            className: "table_td_align_right",
            amount: true,
          },
          {
            caption: "状态",
            fieldName: "jxcjzt",
            isFixed: false,
            isVisible: true,
            isSubTitle: false,
            width: 60,
            align: "center",
            type: "jx",
          },
        ],
      },
      {
        id: "jxfpwrz",
        caption: "进项发票（未认证）",
        isVisible: false,
        isMustSelect: false,
        align: "",
        fieldName: "jxfpwrz",
        width: 320,
        children: [
          {
            caption: "份数",
            fieldName: "jxfpfswrz",
            isFixed: false,
            isVisible: true,
            isSubTitle: true,
            width: 80,
            align: "",
            amount: false,
          },
          {
            caption: "金额",
            fieldName: "jxhjjewrz",
            isFixed: false,
            isVisible: true,
            isSubTitle: true,
            //width: 120,
            align: "",
            className: "table_td_align_right",
            amount: true,
          },
          {
            caption: "税额",
            fieldName: "jxhjsewrz",
            isFixed: false,
            isVisible: true,
            isSubTitle: true,
            //width: 120,
            align: "",
            className: "table_td_align_right",
            amount: true,
          },
          {
            caption: "状态",
            fieldName: "jxcjzt",
            isFixed: false,
            isVisible: true,
            isSubTitle: false,
            width: 60,
            align: "center",
            type: "jx",
          },
        ],
      },
      {
        id: "sqldse",
        caption: "上期留抵税额",
        fieldName: "sqldse",
        isFixed: false,
        isVisible: true,
        width: 120,
        isMustSelect: false,
        align: "",
        className: "table_td_align_right",
        amount: true, // 是否转千分位
      },
      {
        id: "ygse",
        caption: "预估税额",
        fieldName: "ygse",
        isFixed: false,
        isVisible: true,
        isMustSelect: false,
        width: 120,
        align: "",
        className: "table_td_align_right",
        amount: true,
      },
      {
        id: "operation",
        caption: "操作",
        fieldName: "operation",
        isFixed: "right",
        isVisible: true,
        isMustSelect: true,
        width: 130,
        align: "center",
        className: "operation",
        amount: false,
      },
    ],
    columnsOld: ["khmc", "sqldse", "xxfp", "jxfpyrz", "ygse", "operation"],
    pageId: "发票台账（一般纳税人）",
  },
  1: {
    columns: [
      {
        id: "khmc",
        caption: "客户名称",
        fieldName: "khmc",
        isFixed: true,
        isVisible: true,
        width: 290,
        isMustSelect: true,
        align: "",
      },
      {
        id: "mneCode",
        caption: "助记码",
        fieldName: "mneCode",
        isFixed: false,
        isVisible: false,
        width: 100,
        isMustSelect: false,
        align: "",
      },
      {
        id: "cwbbType",
        caption: "纳税期限",
        fieldName: "cwbbType",
        isFixed: false,
        isVisible: true,
        width: 100,
        isMustSelect: false,
        align: "center",
      },
      {
        id: "xxfp",
        caption: "销项发票",
        fieldName: "xxfp",
        isVisible: true,
        isMustSelect: true,
        align: "",
        width: 400,
        children: [
          {
            caption: "份数",
            fieldName: "xxfpfs",
            isFixed: false,
            isVisible: true,
            isSubTitle: true,
            width: 80,
            align: "",
            amount: false,
          },
          {
            caption: "金额",
            fieldName: "xxhjje",
            isFixed: false,
            isVisible: true,
            isSubTitle: true,
            //width: 120,
            align: "",
            className: "table_td_align_right",
            amount: true,
          },
          {
            caption: "税额",
            fieldName: "xxhjse",
            isFixed: false,
            isVisible: true,
            isSubTitle: true,
            //width: 120,
            align: "",
            className: "table_td_align_right",
            isToolTip: true,
            type: "xx",
            amount: true,
          },
          {
            caption: "状态",
            fieldName: "xxcjzt",
            isFixed: false,
            isVisible: true,
            isSubTitle: false,
            width: 60,
            align: "center",
            type: "xx",
          },
        ],
      },
      {
        id: "totalAmount",
        caption: "连续12个月累计",
        fieldName: "totalAmount",
        isFixed: false,
        isVisible: true,
        width: 140,
        isMustSelect: false,
        align: "",
        className: "table_td_align_right",
        amount: true,
        children: [
          {
            caption: "份数",
            fieldName: "totalAmountfs",
            isFixed: false,
            isVisible: true,
            isSubTitle: true,
            width: 80,
            align: "",
            amount: false,
          },
          {
            caption: "销售额",
            fieldName: "totalAmount",
            isFixed: false,
            isVisible: true,
            width: 140,
            isSubTitle: true,
            className: "table_td_align_right",
            align: "",
            amount: true,
          },
        ],
      },
      {
        id: "jxfpyrz",
        caption: "进项发票",
        isVisible: true,
        isMustSelect: true,
        align: "center",
        fieldName: "jxfpyrz",
        width: 400,
        children: [
          {
            caption: "份数",
            fieldName: "jxfpfsyrz",
            isFixed: false,
            isVisible: true,
            isSubTitle: true,
            width: 80,
            align: "",
            amount: false,
          },
          {
            caption: "金额",
            fieldName: "jxhjjeyrz",
            isFixed: false,
            isVisible: true,
            isSubTitle: true,
            className: "table_td_align_right",
            align: "",
            amount: true,
          },
          {
            caption: "税额",
            fieldName: "jxhjseyrz",
            isFixed: false,
            isVisible: true,
            isSubTitle: true,
            // width: 120,
            align: "",
            className: "table_td_align_right",
            isToolTip: true,
            type: "jx",
            amount: true,
          },
          {
            caption: "状态",
            fieldName: "jxcjzt",
            isFixed: false,
            isVisible: true,
            isSubTitle: false,
            width: 60,
            align: "center",
            type: "jx",
          },
        ],
      },
      {
        id: "operation",
        caption: "操作",
        fieldName: "operation",
        isFixed: "right",
        isVisible: true,
        isMustSelect: true,
        width: 100,
        align: "center",
        amount: false,
        className: "operation",
      },
    ],
    columnsOld: ["khmc", "cwbbType", "xxfp", "jxfpyrz", "ygse", "operation"],
    pageId: "发票台账（小规模税人）",
  },
}

export const retCol = [
  {
    title: "发票月份",
    dataIndex: "skssq",
    width: 100,
  },
  {
    title: "提取发票",
    children: [
      {
        title: "销项",
        dataIndex: "xxfp",
        width: 180,
      },
      {
        title: "销项",
        dataIndex: "jxfp",
        width: 180,
      },
    ],
  },
]
