export function getMeta() {
    return {
        name: 'root',
        component: 'Layout',
        className: 'ttk-es-app-open-operate',
        // children:'{{$renderChildren}}'
        children:[
            {
                name:'top',
                component:'::div',
                className:'ttk-es-app-open-operate-top',
                children:[
                    {
                        name:'control',
                        component:'::div',
                        className:'ttk-es-app-open-operate-top-control',
                        children:[
                            {
                                name:'title1',
                                component:'::div',
                                className:'ttk-es-app-open-operate-top-control-title1',
                                children:'代账运营管理'
                            },
                            {
                                name:'title2',
                                component:'::div',
                                className:'ttk-es-app-open-operate-top-control-title2',
                                children:'一站式综合管理平台 专业 智能 高效 实用'
                            },
                            {
                                name:'title3',
                                component:'::div',
                                className:'ttk-es-app-open-operate-top-control-title3',
                                children:'适应于财税服务机构（中小企业、财税从业者、个人）'
                            },
                            {
                                name:'button',
                                component:'Button',
                                className:'ttk-es-app-open-operate-top-control-button',
                                children:'{{data.operateText}}',
                                loading:'{{data.loading}}',
                                // shape:'circle',
                                onClick:'{{$openItOperate}}',
                                disabled:'{{data.showOpen}}'
                            },
                        ]
                    },
                    {
                        name: 'img',
                        component: '::img',
                        className:'ttk-es-app-open-operate-top-img',
                        src: 'https://cloud-manager.oss-cn-beijing.aliyuncs.com/xdz/ope/top.png'
                    }
                ]
            },
            {
                name:'detail',
                component:'::div',
                className:'ttk-es-app-open-operate-detail',
                children:[
                    {
                        name:'title',
                        component:'::div',
                        className:'ttk-es-app-open-operate-detail-title',
                        children:[
                            {
                                name:'title1',
                                component:'::div',
                                className:'ttk-es-app-open-operate-detail-title1',
                                children:'代账运营管理'
                            },
                            {
                                name:'title2',
                                component:'::div',
                                className:'ttk-es-app-open-operate-detail-title2',
                                children:'一款集成商机、客户、合同、收费、任务、员工管理的一站式综合管理平台'
                            }
                        ]
                    },
                    {
                        name:'items',
                        component:'::div',
                        className:'ttk-es-app-open-operate-detail-items',
                        children:[
                            {
                                name:'item1',
                                component:'::div',
                                className:'ttk-es-app-open-operate-detail-items-item',
                                children:[
                                    {
                                        name:'title',
                                        component:'::div',
                                        className:'ttk-es-app-open-operate-detail-items-item-title',
                                        children:'商机'
                                    },
                                    {
                                        name:'detail1',
                                        component:'::div',
                                        className:'ttk-es-app-open-operate-detail-items-item-detail',
                                        children:'全员营销，多渠道智能获客'
                                    },
                                    {
                                        name:'detail2',
                                        component:'::div',
                                        className:'ttk-es-app-open-operate-detail-items-item-detail',
                                        children:'直接查看用户画像，全方面了解企业'
                                    }
                                ]
                            },
                            {
                                name:'item2',
                                component:'::div',
                                className:'ttk-es-app-open-operate-detail-items-item',
                                children:[
                                    {
                                        name:'title',
                                        component:'::div',
                                        className:'ttk-es-app-open-operate-detail-items-item-title',
                                        children:'客户'
                                    },
                                    {
                                        name:'detail',
                                        component:'::div',
                                        className:'ttk-es-app-open-operate-detail-items-item-detail',
                                        children:'同意管理和分配客户资源，交接资料电子化规范管理，沟通信息全流程跟踪'
                                    }
                                ]
                            },
                            {
                                name:'item3',
                                component:'::div',
                                className:'ttk-es-app-open-operate-detail-items-item',
                                children:[
                                    {
                                        name:'title',
                                        component:'::div',
                                        className:'ttk-es-app-open-operate-detail-items-item-title',
                                        children:'服务'
                                    },
                                    {
                                        name:'detail',
                                        component:'::div',
                                        className:'ttk-es-app-open-operate-detail-items-item-detail',
                                        children:'工作进度实时预警提醒，高效协同办公，任务进度实时跟进'
                                    }
                                ]
                            }
                        ]
                    },
                ]
            },
            {
                name:'tip1',
                component:'::div',
                className:'ttk-es-app-open-operate-tip1',
                children:[
                    {
                        name:'detail',
                        component:'::div',
                        className:'ttk-es-app-open-operate-tip1-detail',
                        children:[
                            {
                                name:'title',
                                component:'::div',
                                className:'ttk-es-app-open-operate-tip1-detail-title',
                                children:'工作进度实时预警提醒'
                            },
                            {
                                name:'list',
                                component:'::div',
                                className:'ttk-es-app-open-operate-tip1-detail-list',
                                children:'对收费、合同、任务、记账等工作进度实时预警提醒，避免工作遗漏、提升服务质量、高效协同办公。'
                            },
                            {
                                name:'list',
                                component:'::div',
                                className:'ttk-es-app-open-operate-tip1-detail-list',
                                children:'服务标准化管理，服务流程高度自定义；任务进度实时跟进、反馈；任务分配更简单、高效；工作效率大大提高。'
                            }
                        ]
                    },
                    {
                        name:'img',
                        component:'::img',
                        className:'ttk-es-app-open-operate-tip1-img',
                        src: 'https://cloud-manager.oss-cn-beijing.aliyuncs.com/xdz/ope/detail1.png'
                    }
                ]
            },
            {
                name:'tip2',
                component:'::div',
                className:'ttk-es-app-open-operate-tip2',
                children:[
                    {
                        name:'img',
                        component:'::img',
                        className:'ttk-es-app-open-operate-tip2-img',
                        src: 'https://cloud-manager.oss-cn-beijing.aliyuncs.com/xdz/ope/detail2.png'
                    },
                    {
                        name:'detail',
                        component:'::div',
                        className:'ttk-es-app-open-operate-tip2-detail',
                        children:[
                            {
                                name:'title',
                                component:'::div',
                                className:'ttk-es-app-open-operate-tip2-detail-title',
                                children:'统一管理分配客户资源'
                            },
                            {
                                name:'list',
                                component:'::div',
                                className:'ttk-es-app-open-operate-tip2-detail-list',
                                children:'高效有序的商机、客户、合同、收费、任务管理，等全生命周期的服务。'
                            },
                            {
                                name:'list',
                                component:'::div',
                                className:'ttk-es-app-open-operate-tip2-detail-list',
                                children:'交接资料电子化规范管理，可快捷查询与同事、客户资料往来等。'
                            },
                            {
                                name:'list',
                                component:'::div',
                                className:'ttk-es-app-open-operate-tip2-detail-list',
                                children:'收费与合同关联展示，各业务模块沟通信息全流程跟踪。'
                            }
                        ]
                    }
                ]
            },
            {
                name:'tip3',
                component:'::div',
                className:'ttk-es-app-open-operate-tip3',
                children:[
                    {
                        name:'detail',
                        component:'::div',
                        className:'ttk-es-app-open-operate-tip3-detail',
                        children:[
                            {
                                name:'title',
                                component:'::div',
                                className:'ttk-es-app-open-operate-tip3-detail-title',
                                children:'全员营销 智能获客'
                            },
                            {
                                name:'list',
                                component:'::div',
                                className:'ttk-es-app-open-operate-tip3-detail-list',
                                children:'根据生成的商机线索，可以直接查看用户画像，全方面了解企业的纳税情况、财务情况、发票情况等信息。'
                            },
                            {
                                name:'list',
                                component:'::div',
                                className:'ttk-es-app-open-operate-tip3-detail-list',
                                children:'员工可以通过个人专属二维码进行推广宣传等。'
                            }
                        ]
                    },
                    {
                        name:'img',
                        component:'::img',
                        className:'ttk-es-app-open-operate-tip3-img',
                        src: 'https://cloud-manager.oss-cn-beijing.aliyuncs.com/xdz/ope/detail3.png'
                    }
                ]
            },
        ]
    }
}

export function getInitState() {
    return {
        data:{
            finalNum:0,
            allNum:0,
            progressValue:55,
            downloads:[],
            statusType:{
                '1':'下载成功',
                '2':'下载失败',
                '3':'下载中',
            },
            loading:false,
            operateText:'立即使用',
            showOpen:true,
        }
    }
}