
export const columnData = [
    {
        id: 'jxfpwrz',
        caption: '暂估存货',
        fieldName: 'xxfp',
        isVisible: true,
        isMustSelect: true,
        align: '',
        flexGrow: 1,
        children: [
            { 
                "orgId": 6535301397822464,
                "userId": 6120841777214464,
                "id": 40000500002, 
                "columnId": 400005, 
                "fieldName": "code", 
                "caption": "存货编号", 
                'align': 'center',
                'class': `table_td_align_center`,
                "idFieldType": 1000040003, 
                "width": 120,  
                minWidth: 100,
                "idAlignType": 1000050002, 
                "colIndex": 30, 
                "idOrderMode": 1000060001,
                "isFixed": false, 
                'isSubTitle':true,
                "isVisible": true, 
                "isMustSelect": false, 
                "isSystem": true, 
                "isHeader": true, 
                "isTotalColumn": false, 
                "isOrderMode": false, 
                "occupyConfig": "10CH", 
                "customDecideVisible": true, 
                "ts": "2019-05-06 14:13:32.0", 
                "createTime": "2019-05-06 14:13:41", 
                "updateTime": "2019-05-06 14:13:41" 
            },
            { 
                "orgId": 6535301397822464,
                "userId": 6120841777214464,
                "id": 40000500002, 
                "columnId": 400005, 
                "fieldName": "inventoryName", 
                "caption": "存货名称", 
                'class': 'table_td_align_div',
                "idFieldType": 1000040003, 
                "width": 120,  
                minWidth: 100,
                flexGrow: 1,
                "idAlignType": 1000050002, 
                "colIndex": 30, 
                "idOrderMode": 1000060001,
                "isFixed": false, 
                "isVisible": true, 
                'isSubTitle':true,
                "isMustSelect": false, 
                "isSystem": true, 
                "isHeader": true, 
                "isTotalColumn": false, 
                "isOrderMode": false, 
                "occupyConfig": "10CH", 
                "customDecideVisible": true, 
                "ts": "2019-05-06 14:13:32.0", 
                "createTime": "2019-05-06 14:13:41", 
                "updateTime": "2019-05-06 14:13:41" 
            },
            { 
                "orgId": 6535301397822464,
                "userId": 6120841777214464,
                "id": 40000500002, 
                "columnId": 400005, 
                "fieldName": "guige", 
                "caption": "规格型号", 
                'align': 'center',
                "idFieldType": 1000040003, 
                'class': `table_td_align_center`,
                "width": 120,  
                minWidth: 100, 
                "idAlignType": 1000050002, 
                "colIndex": 30, 
                "idOrderMode": 1000060001,
                "isFixed": false, 
                "isVisible": true, 
                "isMustSelect": false, 
                "isSystem": true, 
                'isSubTitle':true,
                "isHeader": true, 
                "isTotalColumn": false, 
                "isOrderMode": false, 
                "occupyConfig": "10CH", 
                "customDecideVisible": true, 
                "ts": "2019-05-06 14:13:32.0", 
                "createTime": "2019-05-06 14:13:41", 
                "updateTime": "2019-05-06 14:13:41" 
            },
            { 
                "orgId": 6535301397822464,
                "userId": 6120841777214464,
                "id": 40000500002, 
                "columnId": 400005, 
                "fieldName": "unit", 
                "caption": "计量单位", 
                "idFieldType": 1000040003, 
                "width": 100,  
                minWidth: 100,
                'align': 'center',
                "idAlignType": 1000050002, 
                'class': `table_td_align_center`,
                "colIndex": 30, 
                "idOrderMode": 1000060001,
                "isFixed": false, 
                "isVisible": true, 
                'isSubTitle':true,
                "isMustSelect": false, 
                "isSystem": true, 
                "isHeader": true, 
                "isTotalColumn": false, 
                "isOrderMode": false, 
                "occupyConfig": "10CH", 
                "customDecideVisible": true, 
                "ts": "2019-05-06 14:13:32.0", 
                "createTime": "2019-05-06 14:13:41", 
                "updateTime": "2019-05-06 14:13:41" 
            },
            { 
                "orgId": 6535301397822464,
                "userId": 6120841777214464,
                "id": 40000500002, 
                "columnId": 400005, 
                "fieldName": "supplierName", 
                "caption": "供应商名称", 
                'class': 'table_td_align_div',
                "idFieldType": 1000040003, 
                "width": 120,  
                minWidth: 100,
                flexGrow: 1,
                "idAlignType": 1000050002, 
                "colIndex": 30, 
                "idOrderMode": 1000060001,
                "isFixed": false, 
                "isVisible": true, 
                'isSubTitle':true,
                "isMustSelect": false, 
                "isSystem": true, 
                "isHeader": true, 
                "isTotalColumn": false, 
                "isOrderMode": false, 
                "occupyConfig": "10CH", 
                "customDecideVisible": true, 
                "ts": "2019-05-06 14:13:32.0", 
                "createTime": "2019-05-06 14:13:41", 
                "updateTime": "2019-05-06 14:13:41" 
            }
        ]
    },
    {
        id: 'xxfp',
        caption: '暂估期初',
        fieldName: 'xxfp',
        isVisible: true,
        isMustSelect: true,
        align: '',
        children: [
            { 
                "orgId": 6535301397822464,
                "userId": 6120841777214464,
                "id": 40000500002, 
                "columnId": 400005, 
                "fieldName": "num", 
                "caption": "数量", 
                'timeout': true,
                'tip': true,
                'regex': "^([0-9]+)(?:\.[0-9]{1,2})?$",
                'class': 'table_td_align_div table_td_align_right',
                "idFieldType": 1000040003, 
                "width": 140,  
                minWidth: 100, 
                align: 'left',
                "idAlignType": 1000050002, 
                "colIndex": 30, 
                "idOrderMode": 1000060001,
                "isFixed": false, 
                "isVisible": true, 
                'isSubTitle':true,
                "isMustSelect": false, 
                "isSystem": true, 
                "isHeader": true, 
                "isTotalColumn": false, 
                "isOrderMode": false, 
                "occupyConfig": "10CH", 
                "customDecideVisible": true, 
                "ts": "2019-05-06 14:13:32.0", 
                "createTime": "2019-05-06 14:13:41", 
                "updateTime": "2019-05-06 14:13:41" 
            },
            { 
                "orgId": 6535301397822464,
                "userId": 6120841777214464,
                "id": 40000500002, 
                "columnId": 400005, 
                'class': 'table_td_align_div table_td_align_right',
                "fieldName": "price", 
                "caption": "单价", 
                "idFieldType": 1000040003, 
                "width": 140,  
                minWidth: 100, 
                align: 'right',
                "idAlignType": 1000050002, 
                "colIndex": 30, 
                "idOrderMode": 1000060001,
                "isFixed": false, 
                "isVisible": true, 
                "isMustSelect": false, 
                "isSystem": true, 
                "isHeader": true, 
                'isSubTitle':true,
                "isTotalColumn": false, 
                "isOrderMode": false, 
                "occupyConfig": "10CH", 
                "customDecideVisible": true, 
                "ts": "2019-05-06 14:13:32.0", 
                "createTime": "2019-05-06 14:13:41", 
                "updateTime": "2019-05-06 14:13:41" 
            },
            {
                "orgId": 6535301397822464,
                "userId": 6120841777214464,
                "id": 40000500002, 
                "columnId": 400005, 
                "fieldName": "ybBalance", 
                "caption": "金额", 
                "idFieldType": 1000040003, 
                "width": 140,  
                minWidth: 100, 
                align: 'right',
            // 'class':`table_td_align_right`,
                "idAlignType": 1000050002, 
                "colIndex": 30, 
                "idOrderMode": 1000060001,
                "isFixed": false, 
                "isVisible": true, 
                'class': 'table_td_align_div table_td_align_right',
                'isSubTitle':true,
                "isMustSelect": false, 
                "isSystem": true, 
                "isHeader": true, 
                "isTotalColumn": false, 
                "isOrderMode": false, 
                "occupyConfig": "10CH", 
                "customDecideVisible": true, 
                "ts": "2019-05-06 14:13:32.0", 
                "createTime": "2019-05-06 14:13:41", 
                "updateTime": "2019-05-06 14:13:41" 
            }
        ]
    } 
]

export const tableColumns = [
    {
        name: 'inventoryCode',
        columnKey: 'inventoryCode',
        dataIndex: 'inventoryCode',
        flexGrow: 1,
        width: 90,
        resizeAble: true,
        title: '存货编码',
        align: 'center',
        className: 'dataGrid-tableHeaderNoBoder'
    },{
        name: 'inventoryName',
        columnKey: 'inventoryName',
        dataIndex: 'inventoryName',
        flexGrow: 1,
        width: 200,
        resizeAble: true,
        title: '存货名称',
        align: 'left',
        className: 'dataGrid-tableHeaderNoBoder'
    },{
        name: 'specification',
        columnKey: 'specification',
        dataIndex: 'specification',
        flexGrow: 1,
        width: 80,
        resizeAble: true,
        title: '规格型号',
        align: 'left',
        className: 'dataGrid-tableHeade'
    },{
        name: 'propertyName',
        columnKey: 'propertyName',
        dataIndex: 'propertyName',
        flexGrow: 1,
        width: 100,
        resizeAble: true,
        title: '存货类型',
        align: 'left',
        className: 'dataGrid-tableHeader'
    },{
        name: 'unitName',
        columnKey: 'unitName',
        dataIndex: 'unitName',
        flexGrow: 1,
        width: 60,
        resizeAble: true,
        title: '单位',
        align: 'center',
        className: 'dataGrid-tableHeaderNoBoder'
    },{
        name: 'num',
        columnKey: 'num',
        dataIndex: 'num',
        flexGrow: 1,
        width: 150,
        resizeAble: true,
        title: '数量',
        align: 'right',
        className: 'ant-form-item-required'
    },{
        name: 'price',
        columnKey: 'price',
        dataIndex: 'price',
        flexGrow: 1,
        width: 150,
        resizeAble: true,
        title: '单价',
        align: 'right',
        className: 'ant-form-item-require'
    },{
        name: 'ybBalance',
        columnKey: 'ybBalance',
        dataIndex: 'ybBalance',
        flexGrow: 1,
        width: 150,
        resizeAble: true,
        title: '金额',
        align: 'right',
        className: 'ant-form-item-require'
    }
]



