export function getMeta() {
    return {
        name: "root",
        component: "Layout",
        className: "app-purchase-look",
        onMouseDown: "{{$mousedown}}",
        children: [
            {
                name: "ttk-stock-app-spin",
                className: "ttk-stock-app-spin",
                component: "::div",
                _visible: "{{data.loading}}",
                children: "{{$stockLoading()}}",
            },
            {
                name: "title",
                component: "::div",
                className: "app-purchase-look-title",
                children: "{{data.title.titleName}}",
            },
            {
                name: "form1",
                component: "::div",
                className: "app-purchase-look-form",
                children: [
                    {
                        name: "form-item",
                        component: "::div",
                        className: "app-purchase-look-form-item",
                        children: [
                            {
                                name: "label",
                                component: "::span",
                                className: "app-purchase-look-form-item-label",
                                children: "单据编号：",
                            },
                            {
                                name: "wrapper",
                                component: "::div",
                                className: "app-purchase-look-form-item-control-wrapper",
                                children: "{{data.form.code}}",
                            },
                        ],
                    },
                    {
                        name: "form-item",
                        component: "::div",
                        className: "app-purchase-look-form-item",
                        children: [
                            {
                                name: "label",
                                component: "::span",
                                className: "app-purchase-look-form-item-label",
                                children: "往来单位：",
                            },
                            {
                                name: "wrapper",
                                component: "::div",
                                className: "app-purchase-look-form-item-control-wrapper lg",
                                title: "{{data.form.supplierName}}",
                                children: "{{data.form.supplierName}}",
                            },
                        ],
                    },
                ],
            },
            {
                name: "form2",
                component: "::div",
                className: "app-purchase-look-form",
                children: [
                    {
                        name: "form-item",
                        component: "::span",
                        className: "app-purchase-look-form-item",
                        children: [
                            {
                                name: "label",
                                component: "::div",
                                className: "app-purchase-look-form-item-label",
                                children: "{{data.formList.rkriqi+'：'}}",
                            },
                            {
                                name: "wrapper",
                                component: "::div",
                                className: "app-purchase-look-form-item-control-wrapper",
                                children: "{{data.form.cdate}}",
                            },
                        ],
                    },
                    {
                        name: "form-item",
                        component: "::div",
                        className: "app-purchase-look-form-item",
                        children: [
                            {
                                name: "label",
                                component: "::span",
                                className: "app-purchase-look-form-item-label",
                                children: "发票号码：",
                            },
                            {
                                name: "wrapper",
                                component: "::div",
                                className: "app-purchase-look-form-item-control-wrapper",
                                children: "{{data.form.invNo}}",
                            },
                        ],
                    },
                    {
                        name: "form-item",
                        component: "::div",
                        className: "app-purchase-look-form-item",
                        children: [
                            {
                                name: "label",
                                component: "::span",
                                className: "app-purchase-look-form-item-label",
                                children:
                                    "{{(data.title.titleName == '采购入库单' ? '贷方科目' : '借方科目')+'：'}}",
                            },
                            {
                                name: "wrapper",
                                component: "::div",
                                className: "app-purchase-look-form-item-control-wrapper lg",
                                title: "{{data.form.accountName}}",
                                children: "{{data.form.accountName}}",
                            },
                        ],
                    },
                ],
            },
            {
                name: "table",
                component: "DataGrid",
                scroll: "{{data.tableOption}}",
                style: { minHeight: 312 },
                className: "app-purchase-look-form-details app-purchase-look-alert-Body",
                rowsCount: "{{data.list.length}}",
                headerHeight: 35,
                rowHeight: 35,
                footerHeight: 35,
                enableSequence: true,
                startSequence: 1,
                ellipsis: true,
                // enableSequenceAddDelrow: ' true',
                sequenceFooter: {
                    name: "footer",
                    component: "DataGrid.Cell",
                    children: "合计",
                },
                key: "{{data.other.detailHeight}}",
                readonly: false,
                enableAddDelrow: false,
                allowResizeColumn: true,
                columns: [
                    {
                        name: "inventoryCode",
                        component: "DataGrid.Column",
                        columnKey: "code",
                        flexGrow: 1,
                        width: 75,
                        fixed: "left",
                        header: {
                            name: "header",
                            component: "DataGrid.Cell",
                            className: "dataGrid-tableHeaderNoBoder",
                            children: "存货编号",
                        },
                        cell: {
                            name: "cell",
                            align: "left",
                            component: "DataGrid.TextCell",
                            title: "{{data.list[_rowIndex].inventoryCode}}",
                            value: "{{data.list[_rowIndex].inventoryCode}}",
                            onChange:
                                "{{function(e){$sf('data.list.' + _rowIndex + '.inventoryCode', e.target.value)}}}",
                            _power: "({rowIndex})=>rowIndex",
                        },
                    },
                    {
                        name: "inventoryName1",
                        component: "DataGrid.Column",
                        columnKey: "name",
                        flexGrow: 1,
                        width: 180,
                        fixed: "left",
                        header: {
                            name: "header",
                            component: "DataGrid.Cell",
                            children: "存货名称",
                        },
                        cell: {
                            name: "cell",
                            align: "left",
                            component: "::div",
                            className: "tdChme",
                            children: "{{data.list[_rowIndex].inventoryName}}",
                            style: {
                                lineHeight: "34px",
                                paddingLeft: "10px",
                            },
                            _power: "({rowIndex})=>rowIndex",
                        },
                    },
                    {
                        name: "inventoryGuiGe",
                        component: "DataGrid.Column",
                        columnKey: "size",
                        flexGrow: 1,
                        width: 65,
                        align: "left",
                        fixed: "left",
                        header: {
                            name: "header",
                            component: "DataGrid.Cell",
                            className: "dataGrid-tableHeader",
                            children: "规格型号",
                        },
                        cell: {
                            name: "cell",
                            align: "left",
                            component: "DataGrid.TextCell",
                            title: "{{data.list[_rowIndex].inventoryGuiGe}}",
                            value: "{{data.list[_rowIndex].inventoryGuiGe}}",
                            onChange:
                                "{{function(e){$sf('data.list.' + _rowIndex + '.inventoryGuiGe', e.target.value)}}}",
                            _power: "({rowIndex})=>rowIndex",
                        },
                    },
                    {
                        name: "inventoryUnit",
                        component: "DataGrid.Column",
                        columnKey: "workinventoryUnit",
                        flexGrow: 1,
                        width: 65,
                        align: "left",
                        fixed: "left",
                        header: {
                            name: "header",
                            component: "DataGrid.Cell",
                            className: "dataGrid-tableHeaderNoBoder",
                            children: "单位",
                        },
                        cell: {
                            name: "cell",
                            align: "left",
                            component: "DataGrid.TextCell",
                            title: "{{data.list[_rowIndex].inventoryUnit}}",
                            value: "{{data.list[_rowIndex].inventoryUnit}}",
                            onChange:
                                "{{function(e){$sf('data.list.' + _rowIndex + '.inventoryUnit', e.target.value)}}}",
                            _power: "({rowIndex})=>rowIndex",
                        },
                    },
                    {
                        name: "num2",
                        component: "DataGrid.Column",
                        columnKey: "num",
                        flexGrow: 1,
                        width: 65,
                        align: "center",
                        header: {
                            name: "header",
                            component: "DataGrid.Cell",
                            className: "dataGrid-tableHeaderNoBoder",
                            children: "数量",
                        },
                        cell: {
                            name: "cell",
                            align: "left",
                            style: {
                                whiteSpace: "nowrap",
                                textOverflow: "ellipsis",
                                overflow: "hidden",
                                textAlign: "left",
                            },
                            title: "{{$quantityFormat(data.list[_rowIndex].num, 6)}}",
                            component: "DataGrid.TextCell",
                            value: "{{$quantityFormat(data.list[_rowIndex].num, 6)}}",
                            _power: "({rowIndex})=>rowIndex",
                        },
                        footer: {
                            name: "footer",
                            component: "DataGrid.Cell",
                            style: {
                                whiteSpace: "nowrap",
                                textOverflow: "ellipsis",
                                overflow: "hidden",
                            },
                            className: "mk-datagrid-cellContent-left",
                            children: "{{data.listAll.billBodyNum}}",
                            title: "{{data.listAll.billBodyNum}}",
                        },
                    },
                    {
                        name: "price",
                        component: "DataGrid.Column",
                        columnKey: "price",
                        flexGrow: 1,
                        width: 65,
                        align: "center",
                        header: {
                            name: "header",
                            component: "DataGrid.Cell",
                            className: "dataGrid-tableHeaderNoBoder",
                            children: "单价",
                        },
                        cell: {
                            name: "cell",
                            align: "right",
                            style: {
                                whiteSpace: "nowrap",
                                textOverflow: "ellipsis",
                                overflow: "hidden",
                            },
                            title: "{{$quantityFormat(data.list[_rowIndex].price, 6)}}",
                            component: "DataGrid.TextCell",
                            value: "{{$quantityFormat(data.list[_rowIndex].price, 6)}}",
                            _power: "({rowIndex})=>rowIndex",
                        },
                    },
                    {
                        name: "ybbalance",
                        component: "DataGrid.Column",
                        columnKey: "ybbalance",
                        flexGrow: 1,
                        width: 65,
                        align: "center",
                        header: {
                            name: "header",
                            component: "DataGrid.Cell",
                            className: "dataGrid-tableHeaderNoBoder",
                            children: "金额",
                        },
                        cell: {
                            name: "cell",
                            align: "right",
                            style: {
                                whiteSpace: "nowrap",
                                textOverflow: "ellipsis",
                                overflow: "hidden",
                            },
                            timeout: true,
                            tip: true,
                            precision: 2,
                            interceptTab: true,
                            title: "{{$quantityFormat(data.list[_rowIndex].ybbalance, 2)}}",
                            component: "DataGrid.TextCell",
                            value: "{{$quantityFormat(data.list[_rowIndex].ybbalance, 2)}}",
                            _power: "({rowIndex})=>rowIndex",
                        },
                        footer: {
                            name: "footer",
                            component: "DataGrid.Cell",
                            style: {
                                whiteSpace: "nowrap",
                                textOverflow: "ellipsis",
                                overflow: "hidden",
                            },
                            title: "{{data.listAll.billBodyYbBalance}}",
                            className: "mk-datagrid-cellContent-right",
                            children: "{{data.listAll.billBodyYbBalance}}",
                        },
                    },
                    {
                        name: "taxRate",
                        component: "DataGrid.Column",
                        columnKey: "taxRate",
                        flexGrow: 1,
                        width: 65,
                        align: "center",
                        header: {
                            name: "header",
                            component: "DataGrid.Cell",
                            className: "dataGrid-tableHeaderNoBoder",
                            children: "税率",
                        },
                        cell: {
                            name: "cell",
                            align: "right",
                            title: "{{data.list[_rowIndex].taxRate}}",
                            component: "DataGrid.TextCell",
                            value: "{{data.list[_rowIndex].taxRate}}",
                            _power: "({rowIndex})=>rowIndex",
                        },
                    },
                    {
                        name: "tax",
                        component: "DataGrid.Column",
                        columnKey: "tax",
                        flexGrow: 1,
                        width: 65,
                        align: "center",
                        header: {
                            name: "header",
                            component: "DataGrid.Cell",
                            className: "dataGrid-tableHeaderNoBoder",
                            children: "税额",
                        },
                        cell: {
                            name: "cell",
                            align: "right",
                            style: {
                                whiteSpace: "nowrap",
                                textOverflow: "ellipsis",
                                overflow: "hidden",
                            },
                            component: "DataGrid.TextCell",
                            title: "{{data.list[_rowIndex].tax}}",
                            value: "{{data.list[_rowIndex].tax}}",
                            _power: "({rowIndex})=>rowIndex",
                        },
                        footer: {
                            name: "footer",
                            component: "DataGrid.Cell",
                            style: {
                                whiteSpace: "nowrap",
                                textOverflow: "ellipsis",
                                overflow: "hidden",
                            },
                            className: "mk-datagrid-cellContent-right",
                            children: "{{data.listAll.taxAll}}",
                            title: "{{data.listAll.taxAll}}",
                        },
                    },
                    {
                        name: "taxall",
                        component: "DataGrid.Column",
                        columnKey: "taxall",
                        flexGrow: 1,
                        align: "center",
                        width: 65,
                        header: {
                            name: "header",
                            component: "DataGrid.Cell",
                            className: "dataGrid-tableHeaderNoBoder",
                            children: "价税合计",
                        },
                        cell: {
                            name: "cell",
                            align: "right",
                            style: {
                                whiteSpace: "nowrap",
                                textOverflow: "ellipsis",
                                overflow: "hidden",
                            },
                            component: "DataGrid.TextCell",
                            title: "{{data.list[_rowIndex].taxInclusiveAmount}}",
                            value: "{{data.list[_rowIndex].taxInclusiveAmount}}",
                            _power: "({rowIndex})=>rowIndex",
                        },
                        footer: {
                            name: "footer",
                            component: "DataGrid.Cell",
                            className: "mk-datagrid-cellContent-right",
                            style: {
                                whiteSpace: "nowrap",
                                textOverflow: "ellipsis",
                                overflow: "hidden",
                            },
                            children: "{{data.listAll.taxRateAll}}",
                            title: "{{data.listAll.taxRateAll}}",
                        },
                    },
                    {
                        name: "account",
                        component: "DataGrid.Column",
                        _visible: "{{data.title.titleName != '采购入库单'}}",
                        columnKey: "account",
                        flexGrow: 1,
                        width: 125,
                        align: "center",
                        header: {
                            name: "header",
                            component: "DataGrid.Cell",
                            className: "dataGrid-tableHeaderNoBoder",
                            children: "贷方科目",
                        },
                        cell: {
                            name: "cell",
                            align: "left",
                            style: {
                                whiteSpace: "nowrap",
                                textOverflow: "ellipsis",
                                overflow: "hidden",
                            },
                            title: "{{data.list[_rowIndex].accountName}}",
                            component: "DataGrid.TextCell",
                            value: "{{data.list[_rowIndex].accountName}}",
                            _power: "({rowIndex})=>rowIndex",
                        },
                    },
                ],
            },

            {
                name: "footer-btn",
                component: "::div",
                className: "purchase-ru-ku-add-alert-footer-btn",
                style: { bottom: "-52px" },
                children: [
                    {
                        component: "::div",
                        children: "{{'制单人：' + data.form.operater}}",
                    },
                    {
                        name: "btnGroup",
                        component: "::div",
                        className: "purchase-ru-ku-add-alert-footer-btn-btnGroup",
                        children: [
                            {
                                name: "cancel",
                                component: "Button",
                                className: "purchase-ru-ku-add-alert-footer-btn-btnGroup-item",
                                children: "取消",
                                onClick: "{{$onCancel}}",
                            },
                            {
                                _visible: false,
                                name: "confirm",
                                component: "Button",
                                className: "purchase-ru-ku-add-alert-footer-btn-btnGroup-item",
                                type: "primary",
                                children: "保存",
                                onClick: "{{function(e){$save('save')}}}",
                            },
                        ],
                    },
                ],
            },
        ],
    }
}

export function getInitState() {
    return {
        data: {
            title: {
                titleName: "",
            },
            fromType: "",
            // flag: '',
            invNo: "",
            listAll: {
                billBodyNum: "0",
                billBodyYbBalance: "0",
            },
            tableOption: {
                x: 300,
            },
            formList: {
                rkriqi: "",
            },
            form: {
                code: "",
                name: "",
                cdate: "",
                supplierName: "",
                operater: "liucp",
            },
            list: [],
            other: {
                error: {},
            },
            basic: {
                enableDate: "",
            },
            cacheData: [],
            type: "",
        },
    }
}
