export const btnType = [
  {
    name: "sale",
    className: "header-btn",
    type: "primary",
    children: "一键读取发票",
    title: "一键读取进项发票",
    key: "inv-app-pu-collect-card",
  },
  {
    name: "sales",
    className: "header-btn",
    type: "primary",
    children: "票税宝补票",
    title: "票税宝补票",
    key: "psbbupiao",
  },
  {
    name: "sales",
    className: "header-btn",
    type: "primary",
    children: "打印电子票",
    title: "打印电子票",
    key: "printprintInvoices",
  },
]
export const more = [
  {
    type: "import",
    isDisabled: false,
    name: "导入",
    title: "导入进项发票",
  },
  {
    type: "exportInvoice",
    name: "导出",
    title: "导出进项发票",
    isDisabled: true,
  },
  {
    type: "addInvoice",
    name: "新增",
    isDisabled: false,
    hasSub: true,
    subItem: [
      {
        type: "inv-app-new-invoices-card",
        name: "增值税专用发票",
        title: "增值税专用发票(进项)－新增",
        fpzl: "01",
      },
      {
        type: "inv-app-new-invoices-card",
        name: "机动车销售发票",
        title: "机动车销售发票(进项)－新增",
        fpzl: "03",
      },
      {
        type: "inv-app-new-invoices-card",
        name: "增值税普通发票",
        title: "增值税普通发票(进项)－新增",
        sf01: "N",
        fpzl: "04",
      },
      {
        type: "inv-app-new-invoices-card",
        name: "海关专用缴款书",
        title: "海关专用缴款书(进项)－新增",
        sf01: "N",
        fpzl: "13",
      },
      {
        type: "inv-app-new-invoices-card",
        name: "代扣代缴专用缴款书",
        title: "代扣代缴专用缴款书(进项)－新增",
        sf01: "N",
        fpzl: "12",
      },
      {
        type: "inv-app-new-invoices-card",
        name: "农产品销售（收购）发票",
        title: "农产品销售（收购）发票(进项)－新增",
        sf01: "N",
        fpzl: "14",
      },
      {
        type: "inv-app-new-invoices-card",
        name: "通行费增值税电子普通发票",
        title: "通行费增值税电子普通发票(进项)－新增",
        sf01: "N",
        fpzl: "17",
      },
      {
        type: "inv-app-new-invoices-card",
        name: "旅客运输服务抵扣凭证",
        title: "旅客运输服务抵扣凭证(进项)－新增",
        sf01: "N",
        fpzl: "18",
      },
      {
        type: "inv-app-new-invoices-card",
        name: "二手车销售发票",
        title: "二手车销售发票(进项)－新增",
        sf01: "N",
        fpzl: "07",
      },
      {
        type: "inv-app-new-invoices-card",
        name: "其他票据",
        title: "其他票据(进项)－新增",
        sf01: "N",
        fpzl: "99",
      },
    ],
  },
  {
    type: "completionInvoice",
    name: "补全明细",
  },
  {
    type: "deleteInvoice",
    isDisabled: false,
    name: "删除",
  },
  {
    type: "editInvoice",
    isDisabled: false,
    name: "修改",
  },
  {
    type: "batchEditInvoice",
    isDisabled: false,
    name: "批量修改",
  },
]

export const columnData = {
  0: {
    columns: [
      {
        sortTable: true,
        width: 110,
        id: "fpzlMc",
        caption: "发票种类",
        align: "",
        className: "inv-type",
        isVisible: true,
        isMustSelect: true,
        setting: false,
      },
      {
        sortTable: true,
        width: 90,
        id: "showCheck",
        caption: "原始票",
        align: "center",
        className: "",
        isVisible: true,
        isMustSelect: false,
        setting: false,
      },
      {
        sortTable: true,
        width: 90,
        id: "formatedKprq",
        caption: "开票日期",
        align: "center",
        className: "",
        isVisible: true,
        isMustSelect: true,
        setting: false,
      },
      {
        sortTable: true,
        width: 95,
        id: "fpdm",
        caption: "发票代码",
        align: "",
        className: "",
        isVisible: false,
        isMustSelect: false,
        setting: false,
      },
      {
        sortTable: true,
        width: 60,
        id: "fphm",
        caption: "发票号码",
        align: "",
        className: "",
        isVisible: true,
        isMustSelect: true,
        setting: false,
      },
      {
        sortTable: true,
        width: 80,
        id: "dkyf",
        caption: "抵扣月份",
        align: "center",
        className: "",
        isVisible: true,
        isMustSelect: true,
        setting: false,
      },
      {
        sortTable: true,
        width: 80,
        id: "hjje",
        caption: "金额",
        align: "",
        className: "table_td_align_right",
        isVisible: true,
        isMustSelect: true,
      },
      {
        sortTable: true,
        width: 30,
        id: "formatedZbslv",
        caption: "税率",
        align: "",
        className: "table_td_align_right",
        isVisible: true,
        isMustSelect: true,
      },
      {
        sortTable: true,
        width: 80,
        id: "hjse",
        caption: "税额",
        align: "",
        className: "table_td_align_right",
        isVisible: true,
        isMustSelect: true,
      },
      {
        sortTable: true,
        width: 110,
        id: "xfmc",
        caption: "销方名称",
        align: "",
        className: "",
        isVisible: true,
        isMustSelect: true,
      },
      {
        sortTable: true,
        width: 75,
        id: "fpztDm",
        caption: "发票状态",
        align: "center",
        className: "",
        isVisible: true,
        isMustSelect: true,
        setting: false,
      },
      {
        sortTable: true,
        width: 80,
        id: "bdzt",
        caption: "认证状态",
        align: "center",
        className: "",
        isVisible: true,
        isMustSelect: true,
        setting: false,
      },
      {
        sortTable: true,
        width: 80,
        id: "fplyLx",
        caption: "来源",
        align: "center",
        className: "",
        isVisible: true,
        isMustSelect: false,
        setting: false,
      },
      {
        sortTable: false,
        width: 140,
        id: "skssq",
        caption: "发票属期",
        align: "center",
        className: "operation",
        isVisible: true,
        isMustSelect: true,
        setting: true,
      },
    ],
  },
  1: {
    columns: [
      {
        sortTable: true,
        width: 110,
        id: "fpzlMc",
        caption: "发票种类",
        align: "",
        className: "inv-type",
        isVisible: true,
        isMustSelect: true,
        setting: false,
      },
      {
        sortTable: true,
        width: 90,
        id: "showCheck",
        caption: "原始票",
        align: "center",
        className: "",
        isVisible: true,
        isMustSelect: false,
        setting: false,
      },
      {
        sortTable: true,
        width: 90,
        id: "formatedKprq",
        caption: "开票日期",
        align: "center",
        className: "",
        isVisible: true,
        isMustSelect: true,
        setting: false,
      },
      {
        sortTable: true,
        width: 95,
        id: "fpdm",
        caption: "发票代码",
        align: "",
        className: "",
        isVisible: false,
        isMustSelect: false,
        setting: false,
      },
      {
        sortTable: true,
        width: 60,
        id: "fphm",
        caption: "发票号码",
        align: "",
        className: "",
        isVisible: true,
        isMustSelect: true,
        setting: false,
      },
      {
        sortTable: true,
        width: 80,
        id: "hjje",
        caption: "金额",
        align: "",
        className: "table_td_align_right",
        isVisible: true,
        isMustSelect: true,
      },
      {
        sortTable: true,
        width: 30,
        id: "formatedZbslv",
        caption: "税率",
        align: "",
        className: "table_td_align_right",
        isVisible: true,
        isMustSelect: true,
      },
      {
        sortTable: true,
        width: 100,
        id: "hjse",
        caption: "税额",
        align: "",
        className: "table_td_align_right",
        isVisible: true,
        isMustSelect: true,
      },
      {
        sortTable: true,
        width: 180,
        id: "xfmc",
        caption: "销方名称",
        align: "",
        className: "",
        isVisible: true,
        isMustSelect: true,
      },
      {
        sortTable: true,
        width: 75,
        id: "fpztDm",
        caption: "发票状态",
        align: "center",
        className: "",
        isVisible: true,
        isMustSelect: true,
        setting: false,
      },
      {
        sortTable: true,
        width: 100,
        id: "fplyLx",
        caption: "来源",
        align: "center",
        className: "",
        isVisible: true,
        isMustSelect: false,
        setting: false,
      },
      {
        sortTable: false,
        width: 140,
        id: "skssq",
        caption: "发票属期",
        align: "center",
        className: "operation",
        isVisible: true,
        isMustSelect: true,
        setting: true,
      },
    ],
  },
}
export const columnData2 = {
  0: {
    columns: [
      {
        sortTable: true,
        width: 110,
        id: "fpzlMc",
        caption: "发票种类",
        align: "",
        className: "inv-type",
        isVisible: true,
        isMustSelect: false,
        setting: false,
      },
      {
        sortTable: true,
        width: 90,
        id: "showCheck",
        caption: "原始票",
        align: "center",
        className: "",
        isVisible: false,
        isMustSelect: false,
        setting: false,
      },
      {
        sortTable: true,
        width: 90,
        id: "formatedKprq",
        caption: "开票日期",
        align: "center",
        className: "",
        isVisible: true,
        isMustSelect: false,
        setting: false,
      },
      {
        sortTable: true,
        width: 95,
        id: "fpdm",
        caption: "发票代码",
        align: "",
        className: "",
        isVisible: false,
        isMustSelect: false,
        setting: false,
      },
      {
        sortTable: true,
        width: 80,
        id: "fphm",
        caption: "发票号码",
        align: "",
        className: "",
        isVisible: true,
        isMustSelect: true,
        setting: false,
      },
      {
        sortTable: true,
        width: 80,
        id: "dkyf",
        caption: "抵扣月份",
        align: "center",
        className: "",
        isVisible: true,
        isMustSelect: false,
        setting: false,
      },
      {
        sortTable: true,
        width: 80,
        id: "bdlyLx",
        caption: "申报用途",
        align: "center",
        className: "",
        isVisible: false,
        isMustSelect: false,
        setting: false,
      },
      {
        sortTable: true,
        width: 80,
        id: "hjje",
        caption: "金额",
        align: "",
        className: "table_td_align_right",
        isVisible: true,
        isMustSelect: false,
      },
      {
        sortTable: true,
        width: 50,
        id: "formatedZbslv",
        caption: "税率",
        align: "",
        className: "table_td_align_right",
        isVisible: true,
        isMustSelect: false,
      },
      {
        sortTable: true,
        width: 80,
        id: "hjse",
        caption: "税额",
        align: "",
        className: "table_td_align_right",
        isVisible: true,
        isMustSelect: true,
      },
      {
        sortTable: true,
        width: 80,
        id: "nf06",
        caption: "有效税额",
        align: "center",
        className: "",
        isVisible: false,
        isMustSelect: false,
        setting: false,
      },
      {
        sortTable: true,
        width: 180,
        id: "xfmc",
        caption: "销方名称",
        align: "",
        className: "",
        isVisible: true,
        isMustSelect: false,
      },
      {
        sortTable: true,
        width: 75,
        id: "fpztDm",
        caption: "发票状态",
        align: "center",
        className: "",
        isVisible: true,
        isMustSelect: false,
        setting: false,
      },
      {
        sortTable: true,
        width: 80,
        id: "bdjg",
        caption: "管理状态",
        align: "center",
        className: "",
        isVisible: false,
        isMustSelect: false,
        setting: false,
      },
      {
        sortTable: true,
        width: 80,
        id: "bdzt",
        caption: "认证状态",
        align: "center",
        className: "",
        isVisible: true,
        isMustSelect: false,
        setting: false,
      },
      {
        sortTable: true,
        width: 80,
        id: "fplyLx",
        caption: "来源",
        align: "center",
        className: "",
        isVisible: false,
        isMustSelect: false,
        setting: false,
      },
      {
        sortTable: true,
        width: 80,
        id: "df05",
        caption: "上传日期",
        align: "center",
        className: "",
        isVisible: false,
        isMustSelect: false,
        setting: false,
      },
      {
        sortTable: false,
        width: 100,
        id: "skssq",
        caption: "发票属期",
        align: "center",
        className: "operation",
        isVisible: true,
        isMustSelect: true,
        setting: true,
      },
    ],
  },
  1: {
    columns: [
      {
        sortTable: true,
        width: 110,
        id: "fpzlMc",
        caption: "发票种类",
        align: "",
        className: "inv-type",
        isVisible: true,
        isMustSelect: false,
        setting: false,
      },
      {
        sortTable: true,
        width: 90,
        id: "showCheck",
        caption: "原始票",
        align: "center",
        className: "",
        isVisible: false,
        isMustSelect: false,
        setting: false,
      },
      {
        sortTable: true,
        width: 90,
        id: "formatedKprq",
        caption: "开票日期",
        align: "center",
        className: "",
        isVisible: true,
        isMustSelect: false,
        setting: false,
      },
      {
        sortTable: true,
        width: 95,
        id: "fpdm",
        caption: "发票代码",
        align: "",
        className: "",
        isVisible: false,
        isMustSelect: false,
        setting: false,
      },
      {
        sortTable: true,
        width: 80,
        id: "fphm",
        caption: "发票号码",
        align: "",
        className: "",
        isVisible: true,
        isMustSelect: true,
        setting: false,
      },
      {
        sortTable: true,
        width: 80,
        id: "hjje",
        caption: "金额",
        align: "",
        className: "table_td_align_right",
        isVisible: true,
        isMustSelect: false,
      },
      {
        sortTable: true,
        width: 50,
        id: "formatedZbslv",
        caption: "税率",
        align: "",
        className: "table_td_align_right",
        isVisible: true,
        isMustSelect: false,
      },
      {
        sortTable: true,
        width: 80,
        id: "hjse",
        caption: "税额",
        align: "",
        className: "table_td_align_right",
        isVisible: true,
        isMustSelect: true,
      },
      {
        sortTable: true,
        width: 180,
        id: "xfmc",
        caption: "销方名称",
        align: "",
        className: "",
        isVisible: true,
        isMustSelect: false,
      },
      {
        sortTable: true,
        width: 75,
        id: "fpztDm",
        caption: "发票状态",
        align: "center",
        className: "",
        isVisible: true,
        isMustSelect: false,
        setting: false,
      },
      {
        sortTable: true,
        width: 60,
        id: "fplyLx",
        caption: "来源",
        align: "center",
        className: "",
        isVisible: false,
        isMustSelect: false,
        setting: false,
      },
      {
        sortTable: true,
        width: 60,
        id: "df05",
        caption: "上传日期",
        align: "center",
        className: "",
        isVisible: false,
        isMustSelect: false,
        setting: false,
      },
      {
        sortTable: false,
        width: 100,
        id: "skssq",
        caption: "发票属期",
        align: "center",
        className: "operation",
        isVisible: true,
        isMustSelect: true,
        setting: true,
      },
    ],
  },
}

export const filterFormOld = {
  invType: "",
  invCode: "",
  invNumber: "",
  dkMonth: "全部",
  customCode: "",
  taxRate: "",
  strDate: "",
  endDate: "",
  uploadStarDate: "",
  uploadEndDate: "",
  isDzfp: "全部",
  bdlyLx: "抵扣", //申报用途
  bdjg: "正常", // 管理状态
  showCheck: "全部", // 原始票
  statusValue: ["normal", "hcfp"],
  scopeType: 1,
}
