
export const columnData = [
    {
        id: 'inventoryCode',
        caption: "存货编码",
        fieldName: 'inventoryCode',
        isFixed: false,
        isVisible: true,
        width: 80,
        isMustSelect: false,
        className: 'table_td_align_center',
        amount: true
    }, {
        id: 'inventoryName',
        caption: "存货名称",
        fieldName: 'inventoryName',
        isFixed: false,
        isVisible: true,
        width: 130,
        isMustSelect: false,
        className: 'table_td_align_left',
        amount: true
    }, {
        id: 'inventoryGuiGe',
        caption: "规格型号",
        fieldName: 'inventoryGuiGe',
        isFixed: false,
        isVisible: true,
        width: 75,
        isMustSelect: false,
        className: 'table_td_align_left',
        amount: true
    }, {
        id: 'inventoryUnit',
        caption: "单位",
        fieldName: 'inventoryUnit',
        isFixed: false,
        isVisible: true,
        width: 75,
        isMustSelect: false,
        className: 'table_td_align_center',
        amount: true
    },{
        id: 'num',
        caption: "数量",
        fieldName: 'num',
        isFixed: false,
        isVisible: true,
        isSubTitle: true,
        width: 80,
        className: 'table_td_align_right',
        amount: true
    },{
        caption: '收入',
        fieldName: 'xxfp',
        isVisible: true,
        isMustSelect: true,
        children: [{
            id: 'salePrice',
            caption: "单价",
            fieldName: 'salePrice',
            isFixed: false,
            isVisible: true,
            isSubTitle: true,
            width: 80,
            className: 'table_td_align_right',
            amount: true
        }, {
            id: 'saleBalance',
            caption: "金额",
            fieldName: 'saleBalance',
            isFixed: false,
            isVisible: true,
            isSubTitle: true,
            width: 80,
            className: 'table_td_align_right',
            amount: true
        }, ]
    }, {
        id: 'xxfp',
        caption: '成本',
        fieldName: 'xxfp',
        isVisible: true,
        isMustSelect: true,
        children: [ {
            id: 'costPrice',
            caption: "单价",
            fieldName: 'costPrice',
            isFixed: false,
            isVisible: true,
            isSubTitle: true,
            width: 80,
            className: 'table_td_align_right',
            amount: true
        }, {
            id: 'costBalance',
            caption: "金额",
            fieldName: 'costBalance',
            isFixed: false,
            isVisible: true,
            isSubTitle: true,
            width: 80,
            className: 'table_td_align_right',
            amount: true
        }, ]
    },  {
        id: 'profit',
        caption: "毛利",
        fieldName: 'profit',
        isFixed: false,
        isVisible: true,
        width: 80,
        isMustSelect: false,
        className:  'table_td_align_right',
        amount: true
    }, {
        id: 'profitRate',
        caption: "毛利率%",
        fieldName: 'profitRate',
        isFixed: false,
        isVisible: true,
        width: 80,
        isMustSelect: false,
        className:  'table_td_align_right',
        amount: true
    }]