

export const columnField = [
    {
        id: 'inventoryCode',
        name: 'inventoryCode',       
        dataIndex: 'inventoryCode',
        title: "存货编号",
        width: 100,
    }, {
        id: 'inventoryName',
        name: 'inventoryName',
        dataIndex: 'inventoryName',
        title: "存货名称",
        width: 140,
        flexGrow: 1,
    }, {
        id: 'inventoryGuiGe',
        name: 'inventoryGuiGe',
        dataIndex: 'inventoryGuiGe',
        title: "规格型号",
        width: 120,
    }, {
        id: 'inventoryUnit',
        name: 'inventoryUnit',
        dataIndex: 'inventoryUnit',
        title: "单位",
        width: 65,
    }, {
        id: 'kc',
        title: '库存',
        children: [{
            id: 'num',
            dataIndex: 'num',
            align: 'left',
            title: "数量",
            width: 90,  
            sum: true,
            format: 6
        }, {
            id: 'price',
            dataIndex: 'price',
            align: 'right',
            title: "单价",
            width: 90,
        }, {
            id: 'ybbalance',
            dataIndex: 'ybbalance',
            align: 'right',
            title: "金额",
            width: 90,
            sum: true,
            format: 2
        }, ]
    },  {
        id: 'zg',
        title: '暂估',
        children: [{
            id: 'numberChange',
            dataIndex: 'numberChange',
            title: "数量",
            align: 'right',
            width: 110,
            sum: true,
            format: 6
        },{
            id: 'priceChange',
            dataIndex: 'priceChange',
            title: "单价",
            align: 'right',
            width: 110,
        }, {
            id: 'moneryChange',
            dataIndex: 'moneryChange',
            title: "金额",
            align: 'right',
            width: 110,
            sum: true,
            format: 2
        }, ]
    },]